title: "Discord Servers"
description: "Discord Servers List."

author:
  name: "Kitsune Solar"
  email: "kitsune.solar@gmail.com"
  github: "KitsuneSolar"
  twitter: "KitsuneSolar"

webmaster_verifications:
  google: "Mda9LzZFJEJf8-frX8vZiE1kw25IX2IhRl2O_1paAXY"
  yandex: "746d37a02c38a253"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
