title: "Discord Servers"
description: "Discord Servers List."

author:
  name: "Kitsune Solar"
  email: "kitsune.solar@gmail.com"
  github: "KitsuneSolar"
  twitter: "KitsuneSolar"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
